service: sls-proclub-crawler-${self:provider.environment.ENV_ID}

package:
  exclude:
    # - node_modules/**
    - .DS_Store
    - .gitignore
    - .npmignore
    - .git/**
    - .idea/**
    - package.json
    - package-lock.json
    - README.MD
    - data.json
  include:
    - node_modules/axios/
    - node_modules/debug/
    - node_modules/follow-redirects/
    - node_modules/is-buffer/
    - node_modules/ms/

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 300
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.TBL_CLUB_HISTORY}"
        - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.TBL_CLUB_STATS}"
        - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.TBL_MEMBER_HISTORY}"
        - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.TBL_MEMBER_STATS}"

  environment:
    ENV_ID: "terminator"
    CLUB_ID: "132784"
    TBL_CLUB_HISTORY: "FifaClubHistory_${self:provider.environment.ENV_ID}"
    TBL_CLUB_STATS: "FifaClubStats_${self:provider.environment.ENV_ID}"
    TBL_MEMBER_HISTORY: "FifaMemberHistory_${self:provider.environment.ENV_ID}"
    TBL_MEMBER_STATS: "FifaMemberStats_${self:provider.environment.ENV_ID}"
    TIMEZONE_OFFSET_HOURS: -8

functions:
  crawl:
    handler: handler.crawlMatch

  stats:
    handler: handler.saveStats

stepFunctions:
  stateMachines:
    crawlProClub:
      name: crawl-pro-club-${self:provider.environment.ENV_ID}
      events:
        # - http:
        #     path: crawl
        #     method: post
        - schedule:
            rate: rate(60 minutes)
            enabled: true
            input:
              clubId: ${self:provider.environment.CLUB_ID}
        # - schedule:
        #     rate: rate(30 minutes)
        #     enabled: true
        #     input:
        #       clubId: ${self:provider.environment.CLUB_ID_2}
      definition:
        Comment: "ProClub Crawler for ${self:provider.environment.ENV_ID}"
        StartAt: CrawlMatch
        States:
          CrawlMatch:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-crawl"
            Next: SaveStats
          SaveStats:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-stats"
            End: true

resources:
  Resources:
    ClubStatsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: clubId
            AttributeType: S
          - AttributeName: duration
            AttributeType: S
        KeySchema:
          - AttributeName: clubId
            KeyType: HASH
          - AttributeName: duration
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TBL_CLUB_STATS}

    ClubHistoryTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: clubId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: clubId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.TBL_CLUB_HISTORY}

    MemberHistoryTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: playername
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: playername
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.TBL_MEMBER_HISTORY}

    MemberStatsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: playername
            AttributeType: S
          - AttributeName: duration
            AttributeType: S
        KeySchema:
          - AttributeName: playername
            KeyType: HASH
          - AttributeName: duration
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TBL_MEMBER_STATS}